### ISSUE TITLE
Image is broken

### ISSUE THREAD

**Issue by Kerblif** [cracker0dks/whiteboard#180]
Hi

Image on Docker Hub is broken. When I launch it, it throws this:

```
whiteboard-18-whiteboard-1  | Starting server in production mode.
whiteboard-18-whiteboard-1  | /opt/app/scripts/server-backend.js:18
whiteboard-18-whiteboard-1  |     const { createClient } = require("webdav");
whiteboard-18-whiteboard-1  |                              ^
whiteboard-18-whiteboard-1  | 
whiteboard-18-whiteboard-1  | Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/app/node_modules/webdav/dist/node/index.js from /opt/app/scripts/server-backend.js not supported.
whiteboard-18-whiteboard-1  | Instead change the require of index.js in /opt/app/scripts/server-backend.js to a dynamic import() which is available in all CommonJS modules.
whiteboard-18-whiteboard-1  |     at startBackendServer (/opt/app/scripts/server-backend.js:18:30)
whiteboard-18-whiteboard-1  |     at Object.<anonymous> (/opt/app/scripts/server.js:31:5) {
whiteboard-18-whiteboard-1  |   code: 'ERR_REQUIRE_ESM'
whiteboard-18-whiteboard-1  | }
whiteboard-18-whiteboard-1  | npm notice 
whiteboard-18-whiteboard-1  | npm notice New major version of npm available! 8.3.1 -> 10.2.4
whiteboard-18-whiteboard-1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.4>
whiteboard-18-whiteboard-1  | npm notice Run `npm install -g npm@10.2.4` to update!
whiteboard-18-whiteboard-1  | npm notice 
whiteboard-18-whiteboard-1 exited with code 0
```

What am I doing wrong?

**Comment by cracker0dks** [comment]
Sry, my fault. There was this bug in the last version. I fixed that, but missed to pushed the latest docker to docker hub. 
Please try again with the latest image.

**Comment by Kerblif** [comment]
Thanks! Your board is great!
